---
- name: Get the consul bootstrap IP
  shell: getent ahostsv4 {{ consul_bootstrap_hostname }} | grep -v '127.0' | grep 'STREAM' | awk '{print $1}'
  register: consul_ip
  when: not host_natted|bool
  tags: consul_bootstrap

- name: Get the consul bootstrap IP (natted)
  shell: host {{ consul_bootstrap_hostname }} | awk '{print $(NF)}'
  register: consul_ip_natted
  when: host_natted|bool
  tags: consul_bootstrap

- name: Save fact consul bootstrap IP
  set_fact:
    iputils_ip_consul_bootstrap: "{{ consul_ip_natted.stdout | default(consul_ip.stdout) }}"
  tags: consul_bootstrap
